name: PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest

    steps:
      - name: PR Agent Review
        uses: the-pr-agent/pr-agent@main

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          CONFIG.MODEL: google/gemini-2.0-flash

          GOOGLE_AI_STUDIO.GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}